# Generated by Django 2.2.4 on 2019-08-06 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=80)),
                ('address', models.CharField(blank=True, max_length=70)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('state', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(blank=True, max_length=40)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('fax', models.CharField(blank=True, max_length=24)),
                ('email', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateTimeField()),
                ('billing_address', models.CharField(blank=True, max_length=70)),
                ('billing_city', models.CharField(blank=True, max_length=40)),
                ('billing_state', models.CharField(blank=True, max_length=40)),
                ('billing_country', models.CharField(blank=True, max_length=40)),
                ('billing_postal_code', models.CharField(blank=True, max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chinook_media_store.Customer')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('media_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'db_table': 'media_type',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'db_table': 'playlist',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('composer', models.CharField(blank=True, max_length=220)),
                ('milliseconds', models.IntegerField()),
                ('bytes', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chinook_media_store.Album')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chinook_media_store.Genre')),
                ('media_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chinook_media_store.MediaType')),
            ],
            options={
                'db_table': 'track',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('invoice_line_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chinook_media_store.Invoice')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chinook_media_store.Track')),
            ],
            options={
                'db_table': 'invoice_line',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('title', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('hire_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=70)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('state', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(blank=True, max_length=40)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('fax', models.CharField(blank=True, max_length=24)),
                ('email', models.CharField(blank=True, max_length=60)),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chinook_media_store.Employee')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='support_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chinook_media_store.Employee'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chinook_media_store.Artist'),
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('playlist_track_id', models.AutoField(primary_key=True, serialize=False)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chinook_media_store.Playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chinook_media_store.Track')),
            ],
            options={
                'db_table': 'playlist_track',
                'unique_together': {('playlist', 'track')},
            },
        ),
    ]
